name: Gradle Wrapper Validation

on:
  pull_request:
    branches: [ master ]
  push: 
    branches: [ master ]

jobs:
  validateWrapper:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
