# Matches paths that are skipped by PR.yml, to ensure that CI isn't constantly pending.
# See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks

name: Test

on:
  pull_request:
    # Ensure paths match paths-ignore in PR.yml
    paths:
      - 'docs/**'
      - '*.md'
      - 'mkdocs.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
