name: Publish the snapshot version

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  macos-build:
    runs-on: macOS-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v1
    - name: Publish the snapshot artifacts
      env:
        ORG_GRADLE_PROJECT_SONATYPE_NEXUS_USERNAME: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_NEXUS_USERNAME }}
        ORG_GRADLE_PROJECT_SONATYPE_NEXUS_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_NEXUS_PASSWORD }}
        ORG_GRADLE_PROJECT_SQLDELIGHT_BUGSNAG_KEY: ${{ secrets.ORG_GRADLE_PROJECT_SQLDELIGHT_BUGSNAG_KEY }}
        ORG_GRADLE_PROJECT_intellijPublishToken: ${{ secrets.ORG_GRADLE_PROJECT_intellijPublishToken }}
      run: ./gradlew uploadArchives publish publishPlugin --no-daemon

  windows-build:
    runs-on: windows-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v1
      - name: Publish the windows artifact
        env:
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_USERNAME: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_NEXUS_PASSWORD }}
        run: ./gradlew publishMingwPublicationToMavenRepository

env:
  GRADLE_OPTS: "-Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true -Dkotlin.incremental=false"
