name: Extra Renovate Checks

on:
  pull_request:
    paths:
      - '.github/workflows/requirements.txt'

jobs:
  mkdocs_requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Requirements
        run: pip3 install -r .github/workflows/prepare_mkdocs.sh
